### ISSUE TITLE
Major To-Do List

### ISSUE THREAD

**Issue by dvitski** [tempestsbox/ttb#4]
### General
* [x] Tempite Wire doesn't have a length-limit
* [x] Crafting ingredients can't be stacked in the Tempest Crafter
* [x] Staff sounds are too loud
* [x] The Captive Staff suffocates some mobs with larger hitboxes horizontally
* [x] The Extraction Staff doesn't replace basalt and blackstone - terrain, mineable by pickaxes
* [x] The Refrigerant Staff sometimes places a snow layer in mid-air

### Models/Textures
* [ ] Tempite Insulators use the Iron Block model
* [ ] Generic Tempite Wire model/texture non-existent
* [x] Ambient-powered Tempite Stone model/texture non-existent
* [x] Machine right sides and bottom sides have their textures facing the opposite direction (#5)

**Comment by dvitski** [comment]
Any unmarked items in the list are noted elsewhere
